name: Release

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: release

    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v6
      
      - name: Set Release Info
        uses: cuchi/jinja2-action@v1.3.0
        with:
          template: publish.module-template.yaml.j2
          output_file: publish.module-template.yaml
        env:
          PUBLISH_GROUP: net.alphadev
          PUBLISH_VERSION: 1.0.${{github.run_number}}

      - name: Run Build
        run: ./amper build

      - name: Run Tests
        run: ./amper test

      - name: Set up credentials
        run: |
          echo "alphadev.username=GitHub" > local.properties
          echo "alphadev.password=$ALPHADEV_TOKEN" >> local.properties
        env:
          ALPHADEV_TOKEN: ${{ secrets.ALPHADEV_DEPLOY_TOKEN }}

      - name: Release snapshot
        id: release-snapshot
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: 1.0.${{github.run_number}}
          release_name: 1.0.${{github.run_number}}
          draft: false
          prerelease: false

      - name: Publish
        run: ./amper publish alphaDev
